package client_server_comunication;

public enum ServerMessageType {
    QUIT,

    // REGISTRATION
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAIL,

    // LOGIN
    LOGIN,
    LOG_OUT,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    ALREADY_LOGGED_IN,

    // LOBBY CREATION
    CREATE_LOBBY,
    CREATE_LOBBY_SUCCESS,
    CREATE_LOBBY_FAIL,

    // LOBBY MANAGEMENT
    DELETE_LOBBY,
    SET_PLAYER_TO_LOBBY,
    RENAME_LOBBY,
    LOBBY_RENAME_SUCCESS,
    LOBBY_RENAME_FAIL,
    JOIN_LOBBY,
    JOIN_LOBBY_SUCCESS,
    JOIN_LOBBY_FAIL,
    LEAVE_LOBBY,
    REFRESH_LOBBY,
    LOBBY_DISBANDED,

    // GAME
    START_GAME,
    REFRESH_GAME,
    ON_GAME_STARTED,
    GAME_LOST,
    GAME_WON,
}
